/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package bookcms;

import static spark.Spark.*;
import org.sql2o.Sql2o;

public class App {

    public static String resourceDir = System.getProperty("user.dir") + "/src/main/resources";
    public static Sql2o db =
            new Sql2o("jdbc:sqlite:" + resourceDir + "/database/bookcms.db", null, null);

    public static void main(String[] args) {
        configureStaticLocation();
        port(8080);
        new Routes().register();
    }

    public static void configureStaticLocation() {
        String projectDir = System.getProperty("user.dir");
        String staticDir = "/src/main/resources/public";
        staticFiles.externalLocation(projectDir + staticDir);
    }

}
